name: string_scanner
version: 1.3.0
description: A class for parsing strings using a sequence of patterns.
repository: https://github.com/dart-lang/string_scanner
publish_to: none

environment:
  sdk: ^3.5.1

dependencies:
  source_span:
    path: "../source_span"

