name: term_glyph
version: 1.2.2-wip
description: Useful Unicode glyphs and ASCII substitutes.
repository: https://github.com/dart-lang/term_glyph

environment:
  sdk: ^3.5.1

dev_dependencies:
  csv: ^6.0.0
  dart_flutter_team_lints:
    path: "../dart_flutter_team_lints"
  dart_style: ^2.3.6
  test: ^1.25.8
