name: web
version: 1.1.0-wip
description: Lightweight browser API bindings built around JS interop.
repository: https://github.com/dart-lang/web
publish_to: none

environment:
  sdk: ^3.5.1

dev_dependencies:
  dart_flutter_team_lints:
    path: "../../dart_flutter_team_lints"
  path: ^1.9.0
  test: ^1.25.8
