name: image_picker_for_web
description: Web platform implementation of image_picker
version: 3.0.5
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=3.22.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      web:
        pluginClass: ImagePickerPlugin
        fileName: image_picker_for_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  image_picker_platform_interface:
    path: "../image_picker_platform_interface"
  mime:
    path: "../mime"
  web:
    path: "../web/web"

dev_dependencies:
  flutter_test:
    sdk: flutter

topics:
  - camera
  - image-picker
  - files
  - file-selection
