name: matrix2d
description: Matrix 2D is a package for mathematical 2D array functions and manipulations in Dart, similar to NumPy
version: 1.0.4
homepage: "Null"
publish_to: none

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0