name: pixel_color_image
description: >
  Pick the pixel color of a image.
  onHover, onTap, and the Preview widget.
version: 1.2.5


environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  http:
  image: ^4.2.0

dev_dependencies:
  flutter_lints:

flutter:

