name: checks
version: 0.3.1-wip
description: >-
  A framework for checking values against expectations and building custom
  expectations.



environment:
  sdk: ^3.5.1

dependencies:
  async: ^2.11.0
  meta: ^1.15.0
  test_api: ">=0.5.0 <0.8.0"

dev_dependencies:
  test: ^1.25.8
