name: image_picker_ios
description: iOS implementation of the image_picker plugin.
version: 0.8.12
publish_to: none

environment:
  sdk: ^3.5.1
  flutter: ">=3.19.0"

flutter:
  plugin:
    implements: image_picker
    platforms:
      ios:
        dartPluginClass: ImagePickerIOS
        pluginClass: FLTImagePickerPlugin

dependencies:
  flutter:
    sdk: flutter
  image_picker_platform_interface:
    path: "../image_picker_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^22.0.0

topics:
  - camera
  - image-picker
  - files
  - file-selection