name: image_picker_android
description: Android implementation of the image_picker plugin.
publish_to: none
version: 0.8.12+13

environment:
  sdk: ^3.5.1

flutter:
  plugin:
    implements: image_picker
    platforms:
      android:
        package: io.flutter.plugins.imagepicker
        pluginClass: ImagePickerPlugin
        dartPluginClass: ImagePickerAndroid

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle:
    path: "../flutter_plugin_android_lifecycle"
  image_picker_platform_interface:
    path: "../image_picker_platform_interface"

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: 5.4.4
  pigeon: ^22.0.0


topics:
  - camera
  - image-picker
  - files
  - file-selection
