name: pigeon
description: Code generator tool to make communication between Flutter and the host platform type-safe and easier.
version: 22.0.0 # This must match the version in lib/generator_tools.dart

environment:
  sdk: ^3.5.1

dependencies:
  analyzer: ">=5.13.0 <7.0.0"
  args: ^2.5.0
  code_builder: ^4.10.0
  collection: ^1.19.0
  dart_style: ^2.3.6
  meta: ^1.15.0
  path: ^1.9.0
  yaml: ^3.1.2

dev_dependencies:
  test: ^1.25.8

topics:
  - codegen
  - interop
  - platform-channels
  - plugin-development
