name: dart_flutter_team_lints
description: An analysis rule set used by the Dart and Flutter teams.
version: 3.2.0

environment:
  sdk: ^3.5.1

dependencies:
  lints: ^4.0.0

dev_dependencies:
  checks:
    path: "../checks"
  path: ^1.8.0
  test: ^1.0.0
  yaml: ^3.0.0
