name: crop_image
description: An image cropper widget, with 90-degree rotations. Supports mobile, web and desktop.
version: 1.0.13

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
